// ============================================================
// Selah, 시편 쉼표 — 시편 본문 데이터
// ============================================================
// 아래 PSALMS 배열의 각 항목에 시편 1~150편 본문을 채워주세요.
// 저작권 보호를 위해 본문은 비워둔 상태로 제공됩니다.
// 사용 중인 성경(개역개정, 개역한글 등)에서 직접 복사해 넣어주세요.
//
// 형식 예시 (시편 23편):
// {
//   number: 23,
//   title: "다윗의 시",
//   verses: [
//     "여호와는 나의 목자시니 내게 부족함이 없으리로다",
//     "그가 나를 푸른 풀밭에 누이시며 쉴 만한 물 가로 인도하시는도다",
//     "내 영혼을 소생시키고 자기 이름을 위하여 의의 길로 인도하시는도다",
//     "내가 사망의 음침한 골짜기로 다닐지라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라 주의 지팡이와 막대기가 나를 안위하시나이다",
//     "주께서 내 원수의 목전에서 내게 상을 차려 주시고 기름을 내 머리에 부으셨으니 내 잔이 넘치나이다",
//     "내 평생에 선하심과 인자하심이 반드시 나를 따르리니 내가 여호와의 집에 영원히 살리로다"
//   ]
// },
//
// - title: 표제가 없는 시편은 "" (빈 문자열)로 두세요.
// - verses: 절 하나당 배열 항목 하나. 절 번호는 자동으로 매겨집니다.
// - 1편부터 150편까지 순서대로 채워주세요. 순서가 곧 편 순서입니다.
// ============================================================

const PSALMS = [
  { number: 1, title: "", verses: [
    "복 있는 사람은 악인들의 꾀를 따르지 아니하며 죄인들의 길에 서지 아니하며 오만한 자들의 자리에 앉지 아니하고",
    "오직 여호와의 율법을 즐거워하여 그의 율법을 주야로 묵상하는도다",
    "그는 시냇가에 심은 나무가 철을 따라 열매를 맺으며 그 잎사귀가 마르지 아니함 같으니 그가 하는 모든 일이 다 형통하리로다",
    "악인들은 그렇지 아니함이여 오직 바람에 나는 겨와 같도다",
    "그러므로 악인들은 심판을 견디지 못하며 죄인들이 의인들의 모임에 들지 못하리로다",
    "무릇 의인들의 길은 여호와께서 인정하시나 악인들의 길은 망하리로다"
  ] },
  { number: 2, title: "", verses: [
    "어찌하여 이방 나라들이 분노하며 민족들이 헛된 일을 꾸미는가",
    "세상의 군왕들이 나서며 관원들이 서로 꾀하여 여호와와 그의 기름 부음 받은 자를 대적하며",
    "우리가 그들의 맨 것을 끊고 그의 결박을 벗어 버리자 하는도다",
    "하늘에 계신 이가 웃으심이여 주께서 그들을 비웃으시리로다",
    "그 때에 분을 발하며 진노하사 그들을 놀라게 하여 이르시기를",
    "내가 나의 왕을 내 거룩한 산 시온에 세웠다 하시리로다",
    "내가 여호와의 명령을 전하노라 여호와께서 내게 이르시되 너는 내 아들이라 오늘 내가 너를 낳았도다",
    "내게 구하라 내가 이방 나라를 네 유업으로 주리니 네 소유가 땅 끝까지 이르리로다",
    "네가 철장으로 그들을 깨뜨림이여 질그릇 같이 부수리라 하시도다",
    "그런즉 군왕들아 너희는 지혜를 얻으며 세상의 재판관들아 너희는 교훈을 받을지어다",
    "여호와를 경외함으로 섬기고 떨며 즐거워할지어다",
    "그의 아들에게 입맞추라 그렇지 아니하면 진노하심으로 너희가 길에서 망하리니 그의 진노가 급하심이라 여호와께 피하는 모든 사람은 다 복이 있도다"
  ] },
  { number: 3, title: "", verses: [] },
  { number: 4, title: "", verses: [] },
  { number: 5, title: "", verses: [] },
  { number: 6, title: "", verses: [] },
  { number: 7, title: "", verses: [] },
  { number: 8, title: "", verses: [] },
  { number: 9, title: "", verses: [] },
  { number: 10, title: "", verses: [] },
  { number: 11, title: "", verses: [] },
  { number: 12, title: "", verses: [] },
  { number: 13, title: "", verses: [] },
  { number: 14, title: "", verses: [] },
  { number: 15, title: "", verses: [] },
  { number: 16, title: "", verses: [] },
  { number: 17, title: "", verses: [] },
  { number: 18, title: "", verses: [] },
  { number: 19, title: "", verses: [] },
  { number: 20, title: "", verses: [] },
  { number: 21, title: "", verses: [] },
  { number: 22, title: "", verses: [] },
  { number: 23, title: "다윗의 시", verses: [
    "여호와는 나의 목자시니 내게 부족함이 없으리로다",
    "그가 나를 푸른 풀밭에 누이시며 쉴 만한 물 가로 인도하시는도다",
    "내 영혼을 소생시키고 자기 이름을 위하여 의의 길로 인도하시는도다",
    "내가 사망의 음침한 골짜기로 다닐지라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라 주의 지팡이와 막대기가 나를 안위하시나이다",
    "주께서 내 원수의 목전에서 내게 상을 차려 주시고 기름을 내 머리에 부으셨으니 내 잔이 넘치나이다",
    "내 평생에 선하심과 인자하심이 반드시 나를 따르리니 내가 여호와의 집에 영원히 살리로다"
  ] },
  { number: 24, title: "", verses: [] },
  { number: 25, title: "", verses: [] },
  { number: 26, title: "", verses: [] },
  { number: 27, title: "", verses: [] },
  { number: 28, title: "", verses: [] },
  { number: 29, title: "", verses: [] },
  { number: 30, title: "", verses: [] },
  { number: 31, title: "", verses: [] },
  { number: 32, title: "", verses: [] },
  { number: 33, title: "", verses: [] },
  { number: 34, title: "", verses: [] },
  { number: 35, title: "", verses: [] },
  { number: 36, title: "", verses: [] },
  { number: 37, title: "", verses: [] },
  { number: 38, title: "", verses: [] },
  { number: 39, title: "", verses: [] },
  { number: 40, title: "", verses: [] },
  { number: 41, title: "", verses: [] },
  { number: 42, title: "", verses: [] },
  { number: 43, title: "", verses: [] },
  { number: 44, title: "", verses: [] },
  { number: 45, title: "", verses: [] },
  { number: 46, title: "", verses: [] },
  { number: 47, title: "", verses: [] },
  { number: 48, title: "", verses: [] },
  { number: 49, title: "", verses: [] },
  { number: 50, title: "", verses: [] },
  { number: 51, title: "", verses: [] },
  { number: 52, title: "", verses: [] },
  { number: 53, title: "", verses: [] },
  { number: 54, title: "", verses: [] },
  { number: 55, title: "", verses: [] },
  { number: 56, title: "", verses: [] },
  { number: 57, title: "", verses: [] },
  { number: 58, title: "", verses: [] },
  { number: 59, title: "", verses: [] },
  { number: 60, title: "", verses: [] },
  { number: 61, title: "", verses: [] },
  { number: 62, title: "", verses: [] },
  { number: 63, title: "", verses: [] },
  { number: 64, title: "", verses: [] },
  { number: 65, title: "", verses: [] },
  { number: 66, title: "", verses: [] },
  { number: 67, title: "", verses: [] },
  { number: 68, title: "", verses: [] },
  { number: 69, title: "", verses: [] },
  { number: 70, title: "", verses: [] },
  { number: 71, title: "", verses: [] },
  { number: 72, title: "", verses: [] },
  { number: 73, title: "", verses: [] },
  { number: 74, title: "", verses: [] },
  { number: 75, title: "", verses: [] },
  { number: 76, title: "", verses: [] },
  { number: 77, title: "", verses: [] },
  { number: 78, title: "", verses: [] },
  { number: 79, title: "", verses: [] },
  { number: 80, title: "", verses: [] },
  { number: 81, title: "", verses: [] },
  { number: 82, title: "", verses: [] },
  { number: 83, title: "", verses: [] },
  { number: 84, title: "", verses: [] },
  { number: 85, title: "", verses: [] },
  { number: 86, title: "", verses: [] },
  { number: 87, title: "", verses: [] },
  { number: 88, title: "", verses: [] },
  { number: 89, title: "", verses: [] },
  { number: 90, title: "", verses: [] },
  { number: 91, title: "", verses: [] },
  { number: 92, title: "", verses: [] },
  { number: 93, title: "", verses: [] },
  { number: 94, title: "", verses: [] },
  { number: 95, title: "", verses: [] },
  { number: 96, title: "", verses: [] },
  { number: 97, title: "", verses: [] },
  { number: 98, title: "", verses: [] },
  { number: 99, title: "", verses: [] },
  { number: 100, title: "", verses: [] },
  { number: 101, title: "", verses: [] },
  { number: 102, title: "", verses: [] },
  { number: 103, title: "", verses: [] },
  { number: 104, title: "", verses: [] },
  { number: 105, title: "", verses: [] },
  { number: 106, title: "", verses: [] },
  { number: 107, title: "", verses: [] },
  { number: 108, title: "", verses: [] },
  { number: 109, title: "", verses: [] },
  { number: 110, title: "", verses: [] },
  { number: 111, title: "", verses: [] },
  { number: 112, title: "", verses: [] },
  { number: 113, title: "", verses: [] },
  { number: 114, title: "", verses: [] },
  { number: 115, title: "", verses: [] },
  { number: 116, title: "", verses: [] },
  { number: 117, title: "", verses: [] },
  { number: 118, title: "", verses: [] },
  { number: 119, title: "", verses: [] },
  { number: 120, title: "", verses: [] },
  { number: 121, title: "", verses: [] },
  { number: 122, title: "", verses: [] },
  { number: 123, title: "", verses: [] },
  { number: 124, title: "", verses: [] },
  { number: 125, title: "", verses: [] },
  { number: 126, title: "", verses: [] },
  { number: 127, title: "", verses: [] },
  { number: 128, title: "", verses: [] },
  { number: 129, title: "", verses: [] },
  { number: 130, title: "", verses: [] },
  { number: 131, title: "", verses: [] },
  { number: 132, title: "", verses: [] },
  { number: 133, title: "", verses: [] },
  { number: 134, title: "", verses: [] },
  { number: 135, title: "", verses: [] },
  { number: 136, title: "", verses: [] },
  { number: 137, title: "", verses: [] },
  { number: 138, title: "", verses: [] },
  { number: 139, title: "", verses: [] },
  { number: 140, title: "", verses: [] },
  { number: 141, title: "", verses: [] },
  { number: 142, title: "", verses: [] },
  { number: 143, title: "", verses: [] },
  { number: 144, title: "", verses: [] },
  { number: 145, title: "", verses: [] },
  { number: 146, title: "", verses: [] },
  { number: 147, title: "", verses: [] },
  { number: 148, title: "", verses: [] },
  { number: 149, title: "", verses: [] },
  { number: 150, title: "", verses: [] }
];
